name: "backfill-5xC-30m-dclm-stackedu-flat"
description: "30M @ 5xC swarm on DCLM and StackEdu flat"
budget: "ai2/oe-base"
workspace: "ai2/dolma2"
nodes: 1
gpus: 1
variants: 256
preemptible: true
max_tokens: 2_910_233_600
allow_repetition: false 
sequence_length: 2048 # we changed this from 4096 to 2048 to maintain batch size (?)
seed: 42
#mix_temperature: 0.7
minimum_weight: 0.0001
min_strength: 1
max_strength: 20
#sample_multiplier: 50
proxy_model_id: "olmo_30m"
tokenizer: "dolma2"
weka: false
dtype: "uint32"
priority: high
cluster: ai2/augusta-google-1 #ai2/saturn-cirrascale, ai2/neptune-cirrascale
device_batch_size: 32
sources:
  - name: dclm
    topics:
      - name: adult_content
        paths:
          - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/adult_content/dolma-tokenizer/*.npy
      - name: art_and_design
        paths:
          - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/art_and_design/dolma-tokenizer/*.npy
      - name: crime_and_law
        paths:
          - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/crime_and_law/dolma-tokenizer/*.npy
      - name: education_and_jobs
        paths:
          - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/education_and_jobs/dolma-tokenizer/*.npy
      - name: electronics_and_hardware
        paths:
          - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/electronics_and_hardware/dolma-tokenizer/*.npy
      - name: entertainment
        paths:
          - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/entertainment/dolma-tokenizer/*.npy
      - name: fashion_and_beauty
        paths:
          - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/fashion_and_beauty/dolma-tokenizer/*.npy
      - name: finance_and_business
        paths:
          - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/finance_and_business/dolma-tokenizer/*.npy
      - name: food_and_dining
        paths:
          - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/food_and_dining/dolma-tokenizer/*.npy
      - name: games
        paths:
          - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/games/dolma-tokenizer/*.npy
      - name: health
        paths:
          - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/health/dolma-tokenizer/*.npy
      - name: history_and_geography
        paths:
          - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/history_and_geography/dolma-tokenizer/*.npy
      - name: home_and_hobbies
        paths:
          - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/home_and_hobbies/dolma-tokenizer/*.npy
      - name: industrial
        paths:
          - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/industrial/dolma-tokenizer/*.npy
      - name: literature
        paths:
          - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/literature/dolma-tokenizer/*.npy
      - name: politics
        paths:
          - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/politics/dolma-tokenizer/*.npy
      - name: religion
        paths:
          - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/religion/dolma-tokenizer/*.npy
      - name: science_math_and_technology
        paths:
          - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/science_math_and_technology/dolma-tokenizer/*.npy
      - name: social_life
        paths:
          - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/social_life/dolma-tokenizer/*.npy
      - name: software
        paths:
          - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/software/dolma-tokenizer/*.npy
      - name: software_development
        paths:
          - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/software_development/dolma-tokenizer/*.npy
      - name: sports_and_fitness
        paths:
          - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/sports_and_fitness/dolma-tokenizer/*.npy
      - name: transportation
        paths:
          - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/transportation/dolma-tokenizer/*.npy
      - name: travel_and_tourism
        paths:
          - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/travel_and_tourism/dolma-tokenizer/*.npy
  - name: stack-edu
    topics:
      - name: C
        paths:
          - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/C/**/*.npy
      - name: CSharp
        paths:
          - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/CSharp/**/*.npy
      - name: Cpp
        paths:
          - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Cpp/**/*.npy
      - name: Go
        paths:
          - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Go/**/*.npy
      - name: Java
        paths:
          - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Java/**/*.npy
      - name: JavaScript
        paths:
          - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/JavaScript/**/*.npy
      - name: Markdown
        paths:
          - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Markdown/**/*.npy
      - name: PHP
        paths:
          - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/PHP/**/*.npy
      - name: Python
        paths:
          - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Python/**/*.npy
      - name: Ruby
        paths:
          - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Ruby/**/*.npy
      - name: Rust
        paths:
          - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Rust/**/*.npy
      - name: Shell 
        paths:
          - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Shell/**/*.npy
      - name: SQL
        paths:
          - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/SQL/**/*.npy
      - name: Swift
        paths:
          - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Swift/**/*.npy
      - name: TypeScript
        paths:
          - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/TypeScript/**/*.npy
nonzero_weight:
- stack-edu:C
- stack-edu:Cpp
- stack-edu:CSharp
- stack-edu:Go
- stack-edu:Java      
- stack-edu:JavaScript
- stack-edu:Markdown
- stack-edu:PHP
- stack-edu:Python
- stack-edu:Ruby
- stack-edu:Rust
- stack-edu:Shell
- stack-edu:SQL
- stack-edu:Swift
- stack-edu:TypeScript
manual_prior:
  dclm: 0.75
  stack-edu: 0.25