name: 30m-5xC-dclm-centered-0.05-exact-6T-test
description: 30M 5xC swarm of DCLM runs, with manual prior set to be the optimal mix found using log-linear regression, exact computation w/ kl-reg=0.05, at 4x rep 6T (2aacaf87ed42e0e9), test set
budget: ai2/oe-base
workspace: ai2/dolma2
nodes: 1
gpus: 1
variants: 10
preemptible: true
max_tokens: 2910233600
allow_repetition: false
sequence_length: 2048
seed: 42
minimum_weight: 0.05
proxy_model_id: olmo_30m
tokenizer: dolma2
dtype: uint32
weka: true
priority: high
cluster: ai2/jupiter
device_batch_size: 32
sources:
- name: adult_content
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/adult_content/**/*.npy
- name: art_and_design
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/art_and_design/**/*.npy
- name: software_development
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/software_development/**/*.npy
- name: education_and_jobs
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/education_and_jobs/**/*.npy
- name: electronics_and_hardware
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/electronics_and_hardware/**/*.npy
- name: entertainment
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/entertainment/**/*.npy
- name: crime_and_law
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/crime_and_law/**/*.npy
- name: social_life
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/social_life/**/*.npy
- name: fashion_and_beauty
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/fashion_and_beauty/**/*.npy
- name: finance_and_business
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/finance_and_business/**/*.npy
- name: food_and_dining
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/food_and_dining/**/*.npy
- name: games
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/games/**/*.npy
- name: health
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/health/**/*.npy
- name: history_and_geography
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/history_and_geography/**/*.npy
- name: home_and_hobbies
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/home_and_hobbies/**/*.npy
- name: industrial
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/industrial/**/*.npy
- name: literature
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/literature/**/*.npy
- name: politics
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/politics/**/*.npy
- name: religion
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/religion/**/*.npy
- name: science_math_and_technology
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/science_math_and_technology/**/*.npy
- name: software
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/software/**/*.npy
- name: sports_and_fitness
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/sports_and_fitness/**/*.npy
- name: transportation
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/transportation/**/*.npy
- name: travel_and_tourism
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/travel_and_tourism/**/*.npy
manual_prior:
  adult_content: 0.008989070957569886
  art_and_design: 0.010991692180122
  crime_and_law: 0.01362744818184229
  education_and_jobs: 0.029906195584351997
  electronics_and_hardware: 0.040741123935135355
  entertainment: 0.0542186867821194
  fashion_and_beauty: 0.0012439749139619176
  finance_and_business: 0.027738399854180126
  food_and_dining: 0.013680684431966067
  games: 0.03692864930908023
  health: 0.09151284593305506
  history_and_geography: 0.01313680470447379
  home_and_hobbies: 0.01634981025431253
  industrial: 0.021294203124540154
  literature: 0.0521835058355764
  politics: 0.030693273062058667
  religion: 0.014930526079555285
  science_math_and_technology: 0.2847540361442331
  social_life: 0.019081774221241108
  software: 0.038147147087110256
  software_development: 0.14892331618754848
  sports_and_fitness: 0.01816315977624973
  transportation: 0.008158592402629722
  travel_and_tourism: 0.00460507905155222
