name: "dclm-datadelve-1xC-30m"
description: "Mixture of datadelve partitioned dclm sample olmo-30m @ 1xC scale"
budget: "ai2/oe-data"
workspace: "ai2/dolma2"
nodes: 1
gpus: 1
variants: 1
preemptible: true
max_tokens: 600_000_000 # 30_000_000 * 20
sequence_length: 2048
seed: 42
temperature: 0.75
minimum_weight: 0.05
proxy_model_id: "olmo_30m"
tokenizer: "gpt_neox"
dtype: "uint16"
priority: high
cluster: ai2/saturn-cirrascale
sources:
  - name: software_development
    paths:
      - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/gpt-neox-olmo-dolma-v1_5/software_development/**/*.npy
