name: "dclm-datadelve-1xC"
description: "Mixture of datadelve partitioned dclm sample @ 5xC scale"
budget: "ai2/oe-data"
workspace: "ai2/dolma2"
nodes: 1
gpus: 1
variants: 5
preemptible: true
max_tokens: 19_000_000_000 # 190_000_000 * 100
sequence_length: 2048
seed: 42
priority: high
cluster: ai2/s2-cirrascale-l40
sources:
  # TODO: Update these once we have dclm sample tagged
  - name: health
    paths:
      - "s3://ai2-llm/pretraining-data/sources/ds-olmo-data/dclm_partitioned_v0.2/high0/domains_v3.8_tokens/Health/*.npy"
  - name: finance
    paths:
      - "s3://ai2-llm/pretraining-data/sources/ds-olmo-data/dclm_partitioned_v0.2/high0/domains_v3.8_tokens/Finance_n_Business/*.npy"
  - name: entertainment
    paths:
      - "s3://ai2-llm/pretraining-data/sources/ds-olmo-data/dclm_partitioned_v0.2/high0/domains_v3.8_tokens/Entertainment/*.npy"
