name: "dclm-datadelve-1xC"
description: "Mixture of datadelve partitioned dclm sample @ 1xC scale"
budget: "ai2/oe-data"
workspace: "ai2/dolma2"
nodes: 1
gpus: 8
variants: 5
preemptible: true
max_tokens: 3_800_000_000 # 190_000_000 * 20
sequence_length: 2048
seed: 42
priority: normal
cluster: ai2/saturn-cirrascale
sources:
  - name: health
    paths:
      - "s3://ai2-llm/pretraining-data/sources/ds-olmo-data/dclm_partitioned_v0.2/high0/domains_v3.8_tokens/Health/*.npy"
  - name: finance
    paths:
      - "s3://ai2-llm/pretraining-data/sources/ds-olmo-data/dclm_partitioned_v0.2/high0/domains_v3.8_tokens/Finance_n_Business/*.npy"
  - name: entertainment
    paths:
      - "s3://ai2-llm/pretraining-data/sources/ds-olmo-data/dclm_partitioned_v0.2/high0/domains_v3.8_tokens/Entertainment/*.npy"
