name: "example-mixing-experiment"
description: "This is an example mixing experiment configuration file."
budget: "ai2/oe-data"
workspace: "ai2/OLMo-core"
nodes: 1
gpus: 4
variants: 1
preemptible: true
max_tokens: 10_000_000
clusters:
  - ai2/s2-cirrascale-l40
sources:
  - name: "stem"
    paths:
      - "s3://ai2-llm/pretraining-data/sources/ds-olmo-data/dclm_partitioned_v0.2/high0/domains_v3.8_tokens/Science,_Math_n_Technology/*.npy"
  - name: "entertainment"
    paths:
      - "s3://ai2-llm/pretraining-data/sources/ds-olmo-data/dclm_partitioned_v0.2/high0/domains_v3.8_tokens/Entertainment/*.npy"
