name: "5xC-30m-vigintiles"
description: "30M @ 5xC swarm on vigintiles"
budget: "ai2/oe-data"
workspace: "ai2/dolma2"
nodes: 1
gpus: 1
variants: 128
preemptible: true
max_tokens: 2_910_233_600
allow_repetition: false
sequence_length: 2048 # we changed this from 4096 to 2048 to maintain batch size
seed: 42
source_mix_temperature: 0.7 # lower temperature = closer to uniform --> this lets us sample more from the sources with lower priors
topic_mix_temperature: 0.7  # keeping the temperature from the dclm sparse swarm
minimum_weight: 0.05 # ignore
minimum_source_weight: 0.05 # each source must have at least this weight
minimum_topic_weight: 0.05 # each topic must be at least this proportion of its source. higher = more sparse
min_source_strength: 0.1 # higher strength = sample more closely to the prior
max_source_strength: 20
min_topic_strength: 0.1
max_topic_strength: 20
proxy_model_id: "olmo_30m"
tokenizer: "dolma2"
weka: false
dtype: "uint32"
priority: low
cluster: ai2/augusta-google-1 #ai2/saturn-cirrascale, ai2/neptune-cirrascale
device_batch_size: 32
sources:
  - name: vigintile_0002
    paths:
      - s3://ai2-llm/preprocessed/cc_all_dressed/all_dressed_v3/dclm_plus2_vigilantes/allenai/dolma2-tokenizer/*/vigintile_0002/*.npy
  - name: vigintile_0003
    paths:
      - s3://ai2-llm/preprocessed/cc_all_dressed/all_dressed_v3/dclm_plus2_vigilantes/allenai/dolma2-tokenizer/*/vigintile_0003/*.npy
  - name: vigintile_0004
    paths:
      - s3://ai2-llm/preprocessed/cc_all_dressed/all_dressed_v3/dclm_plus2_vigilantes/allenai/dolma2-tokenizer/*/vigintile_0004/*.npy
  - name: vigintile_0005
    paths:
      - s3://ai2-llm/preprocessed/cc_all_dressed/all_dressed_v3/dclm_plus2_vigilantes/allenai/dolma2-tokenizer/*/vigintile_0005/*.npy
  - name: vigintile_0006
    paths:
      - s3://ai2-llm/preprocessed/cc_all_dressed/all_dressed_v3/dclm_plus2_vigilantes/allenai/dolma2-tokenizer/*/vigintile_0006/*.npy
  - name: vigintile_0007
    paths:
      - s3://ai2-llm/preprocessed/cc_all_dressed/all_dressed_v3/dclm_plus2_vigilantes/allenai/dolma2-tokenizer/*/vigintile_0007/*.npy
  - name: vigintile_0008
    paths:
      - s3://ai2-llm/preprocessed/cc_all_dressed/all_dressed_v3/dclm_plus2_vigilantes/allenai/dolma2-tokenizer/*/vigintile_0008/*.npy
  - name: vigintile_0009
    paths:
      - s3://ai2-llm/preprocessed/cc_all_dressed/all_dressed_v3/dclm_plus2_vigilantes/allenai/dolma2-tokenizer/*/vigintile_0009/*.npy
  - name: vigintile_0010
    paths:
      - s3://ai2-llm/preprocessed/cc_all_dressed/all_dressed_v3/dclm_plus2_vigilantes/allenai/dolma2-tokenizer/*/vigintile_0010/*.npy
  - name: vigintile_0011
    paths:
      - s3://ai2-llm/preprocessed/cc_all_dressed/all_dressed_v3/dclm_plus2_vigilantes/allenai/dolma2-tokenizer/*/vigintile_0011/*.npy
  - name: vigintile_0012
    paths:
      - s3://ai2-llm/preprocessed/cc_all_dressed/all_dressed_v3/dclm_plus2_vigilantes/allenai/dolma2-tokenizer/*/vigintile_0012/*.npy
  - name: vigintile_0013
    paths:
      - s3://ai2-llm/preprocessed/cc_all_dressed/all_dressed_v3/dclm_plus2_vigilantes/allenai/dolma2-tokenizer/*/vigintile_0013/*.npy
  - name: vigintile_0014
    paths:
      - s3://ai2-llm/preprocessed/cc_all_dressed/all_dressed_v3/dclm_plus2_vigilantes/allenai/dolma2-tokenizer/*/vigintile_0014/*.npy
  - name: vigintile_0015
    paths:  
      - s3://ai2-llm/preprocessed/cc_all_dressed/all_dressed_v3/dclm_plus2_vigilantes/allenai/dolma2-tokenizer/*/vigintile_0015/*.npy
  - name: vigintile_0016
    paths:
      - s3://ai2-llm/preprocessed/cc_all_dressed/all_dressed_v3/dclm_plus2_vigilantes/allenai/dolma2-tokenizer/*/vigintile_0016/*.npy
  - name: vigintile_0017
    paths:
      - s3://ai2-llm/preprocessed/cc_all_dressed/all_dressed_v3/dclm_plus2_vigilantes/allenai/dolma2-tokenizer/*/vigintile_0017/*.npy
  - name: vigintile_0018
    paths:
      - s3://ai2-llm/preprocessed/cc_all_dressed/all_dressed_v3/dclm_plus2_vigilantes/allenai/dolma2-tokenizer/*/vigintile_0018/*.npy
  - name: vigintile_0020
    paths:
      - s3://ai2-llm/preprocessed/cc_all_dressed/all_dressed_v3/dclm_plus2_vigilantes/allenai/dolma2-tokenizer/*/vigintile_0020/*.npy