sources:
- domain: adult_content
  paths:
  - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/adult_content/dolma2-tokenizer/**/*.npy
  weight: 0.0044008340095919776
- domain: art_and_design
  paths:
  - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/art_and_design/dolma2-tokenizer/**/*.npy
  weight: 0.015540409150593293
- domain: crime_and_law
  paths:
  - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/crime_and_law/dolma2-tokenizer/**/*.npy
  weight: 0.019575159886029116
- domain: education_and_jobs
  paths:
  - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/education_and_jobs/dolma2-tokenizer/**/*.npy
  weight: 0.0155150505706309
- domain: electronics_and_hardware
  paths:
  - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/electronics_and_hardware/dolma2-tokenizer/**/*.npy
  weight: 0.008951579012906484
- domain: entertainment
  paths:
  - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/entertainment/dolma2-tokenizer/**/*.npy
  weight: 0.08760422408654021
- domain: fashion_and_beauty
  paths:
  - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/fashion_and_beauty/dolma2-tokenizer/**/*.npy
  weight: 0.003126228478189813
- domain: finance_and_business
  paths:
  - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/finance_and_business/dolma2-tokenizer/**/*.npy
  weight: 0.09773039483539908
- domain: food_and_dining
  paths:
  - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/food_and_dining/dolma2-tokenizer/**/*.npy
  weight: 0.008620214201767186
- domain: games
  paths:
  - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/games/dolma2-tokenizer/**/*.npy
  weight: 0.05045685535259378
- domain: health
  paths:
  - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/health/dolma2-tokenizer/**/*.npy
  weight: 0.24498778207960575
- domain: history_and_geography
  paths:
  - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/history_and_geography/dolma2-tokenizer/**/*.npy
  weight: 0.010583471929732965
- domain: home_and_hobbies
  paths:
  - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/home_and_hobbies/dolma2-tokenizer/**/*.npy
  weight: 0.013651433608908258
- domain: industrial
  paths:
  - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/industrial/dolma2-tokenizer/**/*.npy
  weight: 0.0038200474351633208
- domain: literature
  paths:
  - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/literature/dolma2-tokenizer/**/*.npy
  weight: 0.020260057708953304
- domain: politics
  paths:
  - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/politics/dolma2-tokenizer/**/*.npy
  weight: 0.12583993735638674
- domain: religion
  paths:
  - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/religion/dolma2-tokenizer/**/*.npy
  weight: 0.03195833530041454
- domain: science_math_and_technology
  paths:
  - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/science_math_and_technology/dolma2-tokenizer/**/*.npy
  weight: 0.14522039462285774
- domain: social_life
  paths:
  - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/social_life/dolma2-tokenizer/**/*.npy
  weight: 0.02792955303579438
- domain: software
  paths:
  - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/software/dolma2-tokenizer/**/*.npy
  weight: 0.00944534956342386
- domain: software_development
  paths:
  - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/software_development/dolma2-tokenizer/**/*.npy
  weight: 0.02048087111844944
- domain: sports_and_fitness
  paths:
  - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/sports_and_fitness/dolma2-tokenizer/**/*.npy
  weight: 0.017743177307625643
- domain: transportation
  paths:
  - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/transportation/dolma2-tokenizer/**/*.npy
  weight: 0.010673489856046344
- domain: travel_and_tourism
  paths:
  - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/travel_and_tourism/dolma2-tokenizer/**/*.npy
  weight: 0.005885149492395872
