sources:
- domain: entertainment
  paths:
  - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/entertainment/dolma2-tokenizer/**/*.npy
  weight: 0.000867592666835428
- domain: finance_and_business
  paths:
  - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/finance_and_business/dolma2-tokenizer/**/*.npy
  weight: 0.00394001348091259
- domain: games
  paths:
  - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/games/dolma2-tokenizer/**/*.npy
  weight: 0.0004934523800221765
- domain: health
  paths:
  - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/health/dolma2-tokenizer/**/*.npy
  weight: 0.4414242329833072
- domain: politics
  paths:
  - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/politics/dolma2-tokenizer/**/*.npy
  weight: 0.0005621550383012255
- domain: science_math_and_technology
  paths:
  - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/science_math_and_technology/dolma2-tokenizer/**/*.npy
  weight: 0.5527125534506214
