sources:
- domain: entertainment
  paths:
  - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/entertainment/dolma2-tokenizer/**/*.npy
  weight: 0.0006503883145775951
- domain: finance_and_business
  paths:
  - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/finance_and_business/dolma2-tokenizer/**/*.npy
  weight: 0.0003321536960961005
- domain: games
  paths:
  - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/games/dolma2-tokenizer/**/*.npy
  weight: 0.0005002131068844
- domain: health
  paths:
  - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/health/dolma2-tokenizer/**/*.npy
  weight: 0.33625391858102593
- domain: politics
  paths:
  - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/politics/dolma2-tokenizer/**/*.npy
  weight: 0.0006149795406675812
- domain: science_math_and_technology
  paths:
  - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/science_math_and_technology/dolma2-tokenizer/**/*.npy
  weight: 0.6616483467607484
