sources:
- domain: entertainment
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/entertainment/**/*.npy
  weight: 0.051807066712541774
- domain: finance_and_business
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/finance_and_business/**/*.npy
  weight: 0.02791057881873803
- domain: games
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/games/**/*.npy
  weight: 0.01934302218751005
- domain: health
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/health/**/*.npy
  weight: 0.09228278704051938
- domain: politics
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/politics/**/*.npy
  weight: 0.03291854832815943
- domain: science_math_and_technology
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/science_math_and_technology/**/*.npy
  weight: 0.7757379969079211
