sources:
- domain: art_and_design
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/art_and_design/**/*.npy
  weight: 0.004742070359207174
- domain: crime_and_law
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/crime_and_law/**/*.npy
  weight: 0.014685351315664312
- domain: education_and_jobs
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/education_and_jobs/**/*.npy
  weight: 0.022342269358933513
- domain: electronics_and_hardware
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/electronics_and_hardware/**/*.npy
  weight: 0.006850369766193201
- domain: entertainment
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/entertainment/**/*.npy
  weight: 0.05639304795713235
- domain: finance_and_business
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/finance_and_business/**/*.npy
  weight: 0.029317526658330782
- domain: games
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/games/**/*.npy
  weight: 0.02238572910239486
- domain: health
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/health/**/*.npy
  weight: 0.1528014881770896
- domain: literature
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/literature/**/*.npy
  weight: 0.052844291170458635
- domain: politics
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/politics/**/*.npy
  weight: 0.029092314973048646
- domain: religion
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/religion/**/*.npy
  weight: 0.015024300175246887
- domain: science_math_and_technology
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/science_math_and_technology/**/*.npy
  weight: 0.18230627389321885
- domain: social_life
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/social_life/**/*.npy
  weight: 0.019752892019435715
- domain: software
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/software/**/*.npy
  weight: 0.008259364947480212
- domain: software_development
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/software_development/**/*.npy
  weight: 0.3528387654942001
- domain: sports_and_fitness
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/sports_and_fitness/**/*.npy
  weight: 0.016705509586542426
- domain: transportation
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/transportation/**/*.npy
  weight: 0.006583296165247535
- domain: travel_and_tourism
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/travel_and_tourism/**/*.npy
  weight: 0.007075138873435842
