sources:
- domain: entertainment
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/entertainment/**/*.npy
  weight: 0.014798824216085393
- domain: finance_and_business
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/finance_and_business/**/*.npy
  weight: 0.004687563819521455
- domain: games
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/games/**/*.npy
  weight: 0.027863043792702265
- domain: health
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/health/**/*.npy
  weight: 0.34272459720229886
- domain: politics
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/politics/**/*.npy
  weight: 0.01190118529144739
- domain: science_math_and_technology
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/science_math_and_technology/**/*.npy
  weight: 0.5980247856702039
