sources:
- domain: crime_and_law
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/crime_and_law/**/*.npy
  weight: 0.02130157593631563
- domain: education_and_jobs
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/education_and_jobs/**/*.npy
  weight: 0.03072572210620221
- domain: entertainment
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/entertainment/**/*.npy
  weight: 0.08193701892583143
- domain: finance_and_business
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/finance_and_business/**/*.npy
  weight: 0.04044995978273122
- domain: games
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/games/**/*.npy
  weight: 0.030846107911710295
- domain: health
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/health/**/*.npy
  weight: 0.1665725376704186
- domain: literature
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/literature/**/*.npy
  weight: 0.05995557788341607
- domain: politics
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/politics/**/*.npy
  weight: 0.03877782067739997
- domain: religion
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/religion/**/*.npy
  weight: 0.02325474902024111
- domain: science_math_and_technology
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/science_math_and_technology/**/*.npy
  weight: 0.2019547300647968
- domain: software
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/software/**/*.npy
  weight: 0.008896518812050036
- domain: software_development
  paths:
  - s3://ai2-llm/preprocessed/dclm/regmixer/v0-sample/allenai/dolma2-tokenizer/software_development/**/*.npy
  weight: 0.29532768120417097
