name: backfill-5xC-30m-superswarm-s2pdf-v2-to-v1-128-exact-opt-prior-1T
description: 30M @ 5xC swarm on s2pdfv1 + dclm + stackedu + algebraicstack + arxiv + finemath + pes2o + wikipedia, with manual topic prior from rep=4 @ 1T, seed=0 128 runs exact (ab0db0b2/e49c7db334cb25c2)
budget: ai2/oe-base
workspace: ai2/dolma2
nodes: 1
gpus: 1
variants: 128
preemptible: true
max_tokens: 2910233600
allow_repetition: false
sequence_length: 2048
seed: 42
minimum_weight: 0.0001
min_strength: 1
max_strength: 20
proxy_model_id: olmo_30m
tokenizer: dolma2
dtype: uint32
priority: normal
cluster: ai2/jupiter
device_batch_size: 32
sources:
- name: algebraicstack
  paths:
  - s3://ai2-llm/preprocessed/proof-pile-2/v0_decontaminated/algebraic-stack/train/allenai/dolma2-tokenizer/**/*.npy
- name: arxiv
  paths:
  - s3://ai2-llm/preprocessed/proof-pile-2/v0_decontaminated/arxiv/train/allenai/dolma2-tokenizer/*.npy
- name: dclm
  topics:
  - name: adult_content
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/adult_content/dolma2-tokenizer/*.npy
  - name: art_and_design
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/art_and_design/dolma2-tokenizer/*.npy
  - name: crime_and_law
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/crime_and_law/dolma2-tokenizer/*.npy
  - name: education_and_jobs
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/education_and_jobs/dolma2-tokenizer/*.npy
  - name: electronics_and_hardware
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/electronics_and_hardware/dolma2-tokenizer/*.npy
  - name: entertainment
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/entertainment/dolma2-tokenizer/*.npy
  - name: fashion_and_beauty
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/fashion_and_beauty/dolma2-tokenizer/*.npy
  - name: finance_and_business
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/finance_and_business/dolma2-tokenizer/*.npy
  - name: food_and_dining
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/food_and_dining/dolma2-tokenizer/*.npy
  - name: games
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/games/dolma2-tokenizer/*.npy
  - name: health
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/health/dolma2-tokenizer/*.npy
  - name: history_and_geography
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/history_and_geography/dolma2-tokenizer/*.npy
  - name: home_and_hobbies
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/home_and_hobbies/dolma2-tokenizer/*.npy
  - name: industrial
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/industrial/dolma2-tokenizer/*.npy
  - name: literature
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/literature/dolma2-tokenizer/*.npy
  - name: politics
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/politics/dolma2-tokenizer/*.npy
  - name: religion
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/religion/dolma2-tokenizer/*.npy
  - name: science_math_and_technology
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/science_math_and_technology/dolma2-tokenizer/*.npy
  - name: social_life
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/social_life/dolma2-tokenizer/*.npy
  - name: software
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/software/dolma2-tokenizer/*.npy
  - name: software_development
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/software_development/dolma2-tokenizer/*.npy
  - name: sports_and_fitness
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/sports_and_fitness/dolma2-tokenizer/*.npy
  - name: transportation
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/transportation/dolma2-tokenizer/*.npy
  - name: travel_and_tourism
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/travel_and_tourism/dolma2-tokenizer/*.npy
- name: stack-edu
  topics:
  - name: C
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/C/**/*.npy
  - name: CSharp
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/CSharp/**/*.npy
  - name: Cpp
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Cpp/**/*.npy
  - name: Go
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Go/**/*.npy
  - name: Java
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Java/**/*.npy
  - name: JavaScript
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/JavaScript/**/*.npy
  - name: Markdown
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Markdown/**/*.npy
  - name: PHP
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/PHP/**/*.npy
  - name: Python
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Python/**/*.npy
  - name: Ruby
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Ruby/**/*.npy
  - name: Rust
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Rust/**/*.npy
  - name: Shell
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Shell/**/*.npy
  - name: SQL
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/SQL/**/*.npy
  - name: Swift
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Swift/**/*.npy
  - name: TypeScript
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/TypeScript/**/*.npy
- name: finemath-3plus
  paths:
  - s3://ai2-llm/preprocessed/finemath/finemath-3plus/allenai/dolma2-tokenizer/*.npy
- name: pes2o
  paths:
  - s3://ai2-llm/preprocessed/pes2o/allenai/dolma2-tokenizer/*.npy
- name: s2pdfv1
  paths:
  - s3://ai2-llm/preprocessed/s2pdf_dedupe_minhash_v1_with_no_pii_basic_quality_datadelve/**/*.npy
- name: wikipedia
  paths:
  - s3://ai2-llm/preprocessed/structured-wikipedia/concat_with_links/allenai/dolma2-tokenizer/*.npy
nonzero_weight:
- algebraicstack
- arxiv
- dclm
- stack-edu
- finemath-3plus
- pes2o
- s2pdfv1
- wikipedia
manual_prior:
  algebraicstack: 0.03111736015265795
  arxiv: 0.03825106242448545
  dclm: 0.5235858749500094
  finemath-3plus: 0.13623189546473086
  pes2o: 0.00786725814559364
  s2pdfv1: 0.04488983444192011
  stack-edu: 0.2118771728196776
  wikipedia: 0.006179541596078886
manual_topic_prior:
  dclm:adult_content: 0.0012978995699272514
  dclm:art_and_design: 0.0014302657572823644
  dclm:crime_and_law: 0.003146599114703351
  dclm:education_and_jobs: 0.014471230017078401
  dclm:electronics_and_hardware: 0.00776733621377092
  dclm:entertainment: 0.04869501887749782
  dclm:fashion_and_beauty: 0.003597226242151225
  dclm:finance_and_business: 0.02633394428273098
  dclm:food_and_dining: 0.009006598528126727
  dclm:games: 0.0037093244511204096
  dclm:health: 0.03898004595235618
  dclm:history_and_geography: 0.012293401527476539
  dclm:home_and_hobbies: 0.06900841104904702
  dclm:industrial: 0.013090738348515108
  dclm:literature: 0.03664056335451869
  dclm:politics: 0.025930778476988
  dclm:religion: 0.0029630930535836106
  dclm:science_math_and_technology: 0.03376471257428713
  dclm:social_life: 0.033034412765339555
  dclm:software: 0.005430027981629592
  dclm:software_development: 0.01590603839240986
  dclm:sports_and_fitness: 0.10720033867599425
  dclm:transportation: 0.0030246671886461803
  dclm:travel_and_tourism: 0.006863202554828341
  stack-edu:C: 0.01729265705735758
  stack-edu:CSharp: 0.0049872352348367946
  stack-edu:Cpp: 0.02329467507824995
  stack-edu:Go: 0.005594380460584961
  stack-edu:Java: 0.008982663131230799
  stack-edu:JavaScript: 0.011733727292761079
  stack-edu:Markdown: 0.02062076767957504
  stack-edu:PHP: 0.011239924909825208
  stack-edu:Python: 0.0720713302124283
  stack-edu:Ruby: 0.00554710321802286
  stack-edu:Rust: 0.005673788517807739
  stack-edu:SQL: 0.0001273219123870893
  stack-edu:Shell: 0.008688506903505084
  stack-edu:Swift: 0.006040076093062052
  stack-edu:TypeScript: 0.009983015118043068
