name: backfill-5xC-30m-dclm-conditional-stackedu-32-exact-seed-2-6T
description: 30M @ 5xC swarm on StackEdu + DCLM, conditional on DCLM p*; rep=4 @ 6T, seed=2 32 DCLM runs exact (5422f1343e4d740a)
budget: ai2/oe-base
workspace: ai2/dolma2
nodes: 1
gpus: 1
variants: 32
preemptible: true
max_tokens: 2910233600
allow_repetition: false
sequence_length: 2048
seed: 2
minimum_weight: 0.0001
min_strength: 1
max_strength: 20
proxy_model_id: olmo_30m
tokenizer: dolma2
weka: false
dtype: uint32
priority: normal
cluster: ai2/augusta-google-1
device_batch_size: 32
sources:
- name: dclm
  topics:
  - name: adult_content
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/adult_content/dolma2-tokenizer/*.npy
    weight: 0.04517338545809768
  - name: art_and_design
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/art_and_design/dolma2-tokenizer/*.npy
    weight: 0.0018136714807133515
  - name: crime_and_law
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/crime_and_law/dolma2-tokenizer/*.npy
    weight: 0.008090544230756216
  - name: education_and_jobs
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/education_and_jobs/dolma2-tokenizer/*.npy
    weight: 0.006016067822698542
  - name: electronics_and_hardware
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/electronics_and_hardware/dolma2-tokenizer/*.npy
    weight: 0.009336579856491303
  - name: entertainment
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/entertainment/dolma2-tokenizer/*.npy
    weight: 0.044929851673584924
  - name: fashion_and_beauty
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/fashion_and_beauty/dolma2-tokenizer/*.npy
    weight: 0.0001385232017409252
  - name: finance_and_business
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/finance_and_business/dolma2-tokenizer/*.npy
    weight: 0.0188292359212452
  - name: food_and_dining
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/food_and_dining/dolma2-tokenizer/*.npy
    weight: 0.04663400452908136
  - name: games
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/games/dolma2-tokenizer/*.npy
    weight: 0.0172215283049305
  - name: health
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/health/dolma2-tokenizer/*.npy
    weight: 0.11688180467444764
  - name: history_and_geography
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/history_and_geography/dolma2-tokenizer/*.npy
    weight: 0.001100615633979195
  - name: home_and_hobbies
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/home_and_hobbies/dolma2-tokenizer/*.npy
    weight: 0.0846071848633345
  - name: industrial
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/industrial/dolma2-tokenizer/*.npy
    weight: 0.001939471591727789
  - name: literature
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/literature/dolma2-tokenizer/*.npy
    weight: 0.03454457086607305
  - name: politics
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/politics/dolma2-tokenizer/*.npy
    weight: 0.07396978843948636
  - name: religion
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/religion/dolma2-tokenizer/*.npy
    weight: 0.009155788148763777
  - name: science_math_and_technology
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/science_math_and_technology/dolma2-tokenizer/*.npy
    weight: 0.2039169824567959
  - name: social_life
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/social_life/dolma2-tokenizer/*.npy
    weight: 2.920674282742753e-05
  - name: software
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/software/dolma2-tokenizer/*.npy
    weight: 0.009843419637188624
  - name: software_development
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/software_development/dolma2-tokenizer/*.npy
    weight: 0.1489233161857701
  - name: sports_and_fitness
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/sports_and_fitness/dolma2-tokenizer/*.npy
    weight: 0.10430028118682438
  - name: transportation
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/transportation/dolma2-tokenizer/*.npy
    weight: 0.002284520622329258
  - name: travel_and_tourism
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/travel_and_tourism/dolma2-tokenizer/*.npy
    weight: 0.010319656464717948
- name: stack-edu
  topics:
  - name: C
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/C/**/*.npy
  - name: CSharp
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/CSharp/**/*.npy
  - name: Cpp
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Cpp/**/*.npy
  - name: Go
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Go/**/*.npy
  - name: Java
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Java/**/*.npy
  - name: JavaScript
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/JavaScript/**/*.npy
  - name: Markdown
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Markdown/**/*.npy
  - name: PHP
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/PHP/**/*.npy
  - name: Python
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Python/**/*.npy
  - name: Ruby
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Ruby/**/*.npy
  - name: Rust
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Rust/**/*.npy
  - name: Shell
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Shell/**/*.npy
  - name: SQL
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/SQL/**/*.npy
  - name: Swift
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Swift/**/*.npy
  - name: TypeScript
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/TypeScript/**/*.npy
nonzero_weight:
- stack-edu:C
- stack-edu:Cpp
- stack-edu:CSharp
- stack-edu:Go
- stack-edu:Java
- stack-edu:JavaScript
- stack-edu:Markdown
- stack-edu:PHP
- stack-edu:Python
- stack-edu:Ruby
- stack-edu:Rust
- stack-edu:Shell
- stack-edu:SQL
- stack-edu:Swift
- stack-edu:TypeScript
manual_prior:
  dclm: 0.75
  stack-edu: 0.25
