name: backfill-5xC-30m-superswarm-add-single-nodes-exact-seed-2-1T
description: 30M @ 5xC swarm on [s2pdfv2, finemath, arxiv, wiki, pes2o, algebraicstack] | [DCLM, StackEdu] p* (rep=4 @ 1T) exact, seed 2 (bb4df6c1/9101825ca30dd39c)
budget: ai2/oe-base
workspace: ai2/dolma2
nodes: 1
gpus: 1
variants: 16
preemptible: true
max_tokens: 2910233600
allow_repetition: false
sequence_length: 2048
seed: 2
minimum_weight: 0.0001
min_strength: 1
max_strength: 20
proxy_model_id: olmo_30m
tokenizer: dolma2
weka: false
dtype: uint32
priority: low
cluster: ai2/augusta-google-1
device_batch_size: 32
sources:
- name: algebraicstack
  paths:
  - s3://ai2-llm/preprocessed/proof-pile-2/v0_decontaminated/algebraic-stack/train/allenai/dolma2-tokenizer/**/*.npy
- name: arxiv
  paths:
  - s3://ai2-llm/preprocessed/proof-pile-2/v0_decontaminated/arxiv/train/allenai/dolma2-tokenizer/*.npy
- name: existing
  topics:
  - name: dclm:adult_content
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/adult_content/dolma2-tokenizer/*.npy
    weight: 0.003886859932611605
  - name: dclm:art_and_design
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/art_and_design/dolma2-tokenizer/*.npy
    weight: 0.006076284316203646
  - name: dclm:crime_and_law
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/crime_and_law/dolma2-tokenizer/*.npy
    weight: 0.0056327641874404
  - name: dclm:education_and_jobs
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/education_and_jobs/dolma2-tokenizer/*.npy
    weight: 0.01258166024765477
  - name: dclm:electronics_and_hardware
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/electronics_and_hardware/dolma2-tokenizer/*.npy
    weight: 0.00680401222457309
  - name: dclm:entertainment
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/entertainment/dolma2-tokenizer/*.npy
    weight: 0.03065986801365948
  - name: dclm:fashion_and_beauty
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/fashion_and_beauty/dolma2-tokenizer/*.npy
    weight: 0.0014920265622305644
  - name: dclm:finance_and_business
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/finance_and_business/dolma2-tokenizer/*.npy
    weight: 0.012035996096625456
  - name: dclm:food_and_dining
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/food_and_dining/dolma2-tokenizer/*.npy
    weight: 0.005476029373795699
  - name: dclm:games
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/games/dolma2-tokenizer/*.npy
    weight: 0.011348641278804712
  - name: dclm:health
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/health/dolma2-tokenizer/*.npy
    weight: 0.06162813990820592
  - name: dclm:history_and_geography
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/history_and_geography/dolma2-tokenizer/*.npy
    weight: 0.012165037363519034
  - name: dclm:home_and_hobbies
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/home_and_hobbies/dolma2-tokenizer/*.npy
    weight: 0.03868269357609693
  - name: dclm:industrial
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/industrial/dolma2-tokenizer/*.npy
    weight: 0.003822930377651782
  - name: dclm:literature
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/literature/dolma2-tokenizer/*.npy
    weight: 0.029856374328725406
  - name: dclm:politics
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/politics/dolma2-tokenizer/*.npy
    weight: 0.01362202835181138
  - name: dclm:religion
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/religion/dolma2-tokenizer/*.npy
    weight: 0.005905452836041313
  - name: dclm:science_math_and_technology
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/science_math_and_technology/dolma2-tokenizer/*.npy
    weight: 0.11547883353955524
  - name: dclm:social_life
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/social_life/dolma2-tokenizer/*.npy
    weight: 0.008315210581413048
  - name: dclm:software
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/software/dolma2-tokenizer/*.npy
    weight: 0.004197568083055142
  - name: dclm:software_development
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/software_development/dolma2-tokenizer/*.npy
    weight: 0.2738355204137029
  - name: dclm:sports_and_fitness
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/sports_and_fitness/dolma2-tokenizer/*.npy
    weight: 0.009012703321009601
  - name: dclm:transportation
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/transportation/dolma2-tokenizer/*.npy
    weight: 0.002770208447753975
  - name: dclm:travel_and_tourism
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/travel_and_tourism/dolma2-tokenizer/*.npy
    weight: 0.002064774525923576
  - name: stack-edu:C
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/C/**/*.npy
    weight: 0.0035647315358971676
  - name: stack-edu:CSharp
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/CSharp/**/*.npy
    weight: 0.028818101327537576
  - name: stack-edu:Cpp
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Cpp/**/*.npy
    weight: 0.05012178296585476
  - name: stack-edu:Go
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Go/**/*.npy
    weight: 0.005594380469178254
  - name: stack-edu:Java
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Java/**/*.npy
    weight: 0.02400929341136649
  - name: stack-edu:JavaScript
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/JavaScript/**/*.npy
    weight: 0.0355478891795193
  - name: stack-edu:Markdown
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Markdown/**/*.npy
    weight: 0.05112894984708629
  - name: stack-edu:PHP
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/PHP/**/*.npy
    weight: 0.01079777399407533
  - name: stack-edu:Python
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Python/**/*.npy
    weight: 0.0720713302311965
  - name: stack-edu:Ruby
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Ruby/**/*.npy
    weight: 0.005547103218475751
  - name: stack-edu:Rust
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Rust/**/*.npy
    weight: 0.005673788522815192
  - name: stack-edu:Shell
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Shell/**/*.npy
    weight: 0.010170551492651836
  - name: stack-edu:SQL
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/SQL/**/*.npy
    weight: 0.0056444040535086875
  - name: stack-edu:Swift
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Swift/**/*.npy
    weight: 0.006040076085892261
  - name: stack-edu:TypeScript
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/TypeScript/**/*.npy
    weight: 0.007918225774759717
- name: finemath-3plus
  paths:
  - s3://ai2-llm/preprocessed/finemath/finemath-3plus/allenai/dolma2-tokenizer/*.npy
- name: pes2o
  paths:
  - s3://ai2-llm/preprocessed/pes2o/allenai/dolma2-tokenizer/*.npy
- name: s2pdfv2
  paths:
  - s3://ai2-llm/preprocessed/s2pdf_dedupe_minhash_v1_with_no_pii_basic_quality_datadelve_norefs_mdtables_v2/**/*.npy
- name: wikipedia
  paths:
  - s3://ai2-llm/preprocessed/structured-wikipedia/concat_with_links/allenai/dolma2-tokenizer/*.npy
nonzero_weight:
- algebraicstack
- arxiv
- existing
- finemath-3plus
- pes2o
- s2pdfv2
- wikipedia
manual_prior:
  algebraicstack: 0.02
  arxiv: 0.04
  existing: 0.7
  finemath-3plus: 0.1
  pes2o: 0.02
  s2pdfv2: 0.1
  wikipedia: 0.02
