name: backfill-5xC-30m-superswarm-add-single-nodes-partial-exact-seed-1-1T
description: 30M @ 5xC swarm on all sources | [DCLM, StackEdu, Software] p* (rep=4 @ 1T) exact seed 1 (a2e827d5/e97541bc9552d37a)
budget: ai2/oe-base
workspace: ai2/dolma2
nodes: 1
gpus: 1
variants: 32
preemptible: true
max_tokens: 2910233600
allow_repetition: false
sequence_length: 2048
seed: 1
minimum_weight: 0.0001
min_strength: 1
max_strength: 25
proxy_model_id: olmo_30m
tokenizer: dolma2
weka: true
dtype: uint32
priority: high
cluster: ai2/titan
device_batch_size: 32
sources:
- name: algebraicstack
  paths:
  - s3://ai2-llm/preprocessed/proof-pile-2/v0_decontaminated/algebraic-stack/train/allenai/dolma2-tokenizer/**/*.npy
- name: arxiv
  paths:
  - s3://ai2-llm/preprocessed/proof-pile-2/v0_decontaminated/arxiv/train/allenai/dolma2-tokenizer/*.npy
- name: dclm
  topics:
  - name: adult_content
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/adult_content/dolma2-tokenizer/*.npy
    weight: 0.007104521229600571
  - name: art_and_design
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/art_and_design/dolma2-tokenizer/*.npy
    weight: 0.012682170980306742
  - name: crime_and_law
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/crime_and_law/dolma2-tokenizer/*.npy
    weight: 0.013012124028147488
  - name: education_and_jobs
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/education_and_jobs/dolma2-tokenizer/*.npy
    weight: 0.027111423435853682
  - name: electronics_and_hardware
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/electronics_and_hardware/dolma2-tokenizer/*.npy
    weight: 0.010045834118789343
  - name: entertainment
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/entertainment/dolma2-tokenizer/*.npy
    weight: 0.062018881876299246
  - name: fashion_and_beauty
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/fashion_and_beauty/dolma2-tokenizer/*.npy
    weight: 0.002935846341048306
  - name: finance_and_business
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/finance_and_business/dolma2-tokenizer/*.npy
    weight: 0.028763502997717343
  - name: food_and_dining
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/food_and_dining/dolma2-tokenizer/*.npy
    weight: 0.0121688468680008
  - name: games
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/games/dolma2-tokenizer/*.npy
    weight: 0.02216229097643923
  - name: health
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/health/dolma2-tokenizer/*.npy
    weight: 0.14194477059506724
  - name: history_and_geography
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/history_and_geography/dolma2-tokenizer/*.npy
    weight: 0.018035914575389618
  - name: home_and_hobbies
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/home_and_hobbies/dolma2-tokenizer/*.npy
    weight: 0.029274989463650408
  - name: industrial
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/industrial/dolma2-tokenizer/*.npy
    weight: 0.03943599935548183
  - name: literature
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/literature/dolma2-tokenizer/*.npy
    weight: 0.07283876014386853
  - name: politics
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/politics/dolma2-tokenizer/*.npy
    weight: 0.02953001116996028
  - name: religion
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/religion/dolma2-tokenizer/*.npy
    weight: 0.01667225323340598
  - name: science_math_and_technology
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/science_math_and_technology/dolma2-tokenizer/*.npy
    weight: 0.2397978348567639
  - name: social_life
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/social_life/dolma2-tokenizer/*.npy
    weight: 0.02030152492849591
  - name: software
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/software/dolma2-tokenizer/*.npy
    weight: 0.008260785164245105
  - name: software_development
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/software_development/dolma2-tokenizer/*.npy
    weight: 0.13231563636591182
  - name: sports_and_fitness
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/sports_and_fitness/dolma2-tokenizer/*.npy
    weight: 0.04079800959728148
  - name: transportation
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/transportation/dolma2-tokenizer/*.npy
    weight: 0.007184117773653343
  - name: travel_and_tourism
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/travel_and_tourism/dolma2-tokenizer/*.npy
    weight: 0.005603949924622078
- name: stack-edu
  topics:
  - name: C
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/C/**/*.npy
    weight: 0.04623985951628164
  - name: CSharp
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/CSharp/**/*.npy
    weight: 0.07035501884846657
  - name: Cpp
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Cpp/**/*.npy
    weight: 0.0192065973782474
  - name: Go
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Go/**/*.npy
    weight: 0.013657830575328829
  - name: Java
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Java/**/*.npy
    weight: 0.19419522373372586
  - name: JavaScript
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/JavaScript/**/*.npy
    weight: 0.06604976052818923
  - name: Markdown
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Markdown/**/*.npy
    weight: 0.23670088219240576
  - name: PHP
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/PHP/**/*.npy
    weight: 0.060983519974277596
  - name: Python
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Python/**/*.npy
    weight: 0.1759512106431592
  - name: Ruby
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Ruby/**/*.npy
    weight: 0.013542410152120965
  - name: Rust
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Rust/**/*.npy
    weight: 0.013851693279386844
  - name: Shell
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Shell/**/*.npy
    weight: 0.02482985735225345
  - name: SQL
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/SQL/**/*.npy
    weight: 0.02531819120568157
  - name: Swift
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Swift/**/*.npy
    weight: 0.014745928761825795
  - name: TypeScript
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/TypeScript/**/*.npy
    weight: 0.024372015858649416
- name: finemath-3plus
  paths:
  - s3://ai2-llm/preprocessed/finemath/finemath-3plus/allenai/dolma2-tokenizer/*.npy
- name: pes2o
  paths:
  - s3://ai2-llm/preprocessed/pes2o/allenai/dolma2-tokenizer/*.npy
- name: s2pdfv2
  paths:
  - s3://ai2-llm/preprocessed/s2pdf_dedupe_minhash_v1_with_no_pii_basic_quality_datadelve_norefs_mdtables_v2/**/*.npy
- name: wikipedia
  paths:
  - s3://ai2-llm/preprocessed/structured-wikipedia/concat_with_links/allenai/dolma2-tokenizer/*.npy
nonzero_weight:
- algebraicstack
- arxiv
- dclm
- finemath-3plus
- pes2o
- s2pdfv2
- stack-edu
- wikipedia
manual_prior:
  algebraicstack: 0.02
  arxiv: 0.04
  dclm: 0.525
  stack-edu: 0.175
  finemath-3plus: 0.1
  pes2o: 0.02
  s2pdfv2: 0.1
  wikipedia: 0.02
