name: backfill-5xC-30m-superswarm-partition-s2pdf-256-exact-opt-prior-1T
description: 30M @ 5xC swarm on s2pdfv1 (partitioned) + dclm + stackedu + arxiv + finemath + pes2o + wikipedia, with manual topic/source prior from rep=4 @ 1T, seed=0 256 runs exact (ebde9854/19983e6dd038862f)
budget: ai2/oe-base
workspace: ai2/dolma2
nodes: 1
gpus: 1
variants: 256
preemptible: true
max_tokens: 2910233600
allow_repetition: false
sequence_length: 2048
seed: 42
minimum_weight: 0.000001
min_strength: 1
max_strength: 20
sample_multiplier: 500
proxy_model_id: olmo_30m
tokenizer: dolma2
weka: false
dtype: uint32
priority: normal
cluster: ai2/jupiter
device_batch_size: 32
sources:
- name: arxiv
  paths:
  - s3://ai2-llm/preprocessed/proof-pile-2/v0_decontaminated/arxiv/train/allenai/dolma2-tokenizer/*.npy
- name: dclm
  topics:
  - name: adult_content
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/adult_content/dolma2-tokenizer/*.npy
  - name: art_and_design
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/art_and_design/dolma2-tokenizer/*.npy
  - name: crime_and_law
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/crime_and_law/dolma2-tokenizer/*.npy
  - name: education_and_jobs
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/education_and_jobs/dolma2-tokenizer/*.npy
  - name: electronics_and_hardware
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/electronics_and_hardware/dolma2-tokenizer/*.npy
  - name: entertainment
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/entertainment/dolma2-tokenizer/*.npy
  - name: fashion_and_beauty
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/fashion_and_beauty/dolma2-tokenizer/*.npy
  - name: finance_and_business
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/finance_and_business/dolma2-tokenizer/*.npy
  - name: food_and_dining
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/food_and_dining/dolma2-tokenizer/*.npy
  - name: games
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/games/dolma2-tokenizer/*.npy
  - name: health
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/health/dolma2-tokenizer/*.npy
  - name: history_and_geography
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/history_and_geography/dolma2-tokenizer/*.npy
  - name: home_and_hobbies
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/home_and_hobbies/dolma2-tokenizer/*.npy
  - name: industrial
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/industrial/dolma2-tokenizer/*.npy
  - name: literature
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/literature/dolma2-tokenizer/*.npy
  - name: politics
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/politics/dolma2-tokenizer/*.npy
  - name: religion
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/religion/dolma2-tokenizer/*.npy
  - name: science_math_and_technology
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/science_math_and_technology/dolma2-tokenizer/*.npy
  - name: social_life
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/social_life/dolma2-tokenizer/*.npy
  - name: software
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/software/dolma2-tokenizer/*.npy
  - name: software_development
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/software_development/dolma2-tokenizer/*.npy
  - name: sports_and_fitness
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/sports_and_fitness/dolma2-tokenizer/*.npy
  - name: transportation
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/transportation/dolma2-tokenizer/*.npy
  - name: travel_and_tourism
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/travel_and_tourism/dolma2-tokenizer/*.npy
- name: stack-edu
  topics:
  - name: C
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/C/**/*.npy
  - name: CSharp
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/CSharp/**/*.npy
  - name: Cpp
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Cpp/**/*.npy
  - name: Go
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Go/**/*.npy
  - name: Java
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Java/**/*.npy
  - name: JavaScript
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/JavaScript/**/*.npy
  - name: Markdown
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Markdown/**/*.npy
  - name: PHP
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/PHP/**/*.npy
  - name: Python
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Python/**/*.npy
  - name: Ruby
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Ruby/**/*.npy
  - name: Rust
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Rust/**/*.npy
  - name: Shell
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Shell/**/*.npy
  - name: SQL
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/SQL/**/*.npy
  - name: Swift
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Swift/**/*.npy
  - name: TypeScript
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/TypeScript/**/*.npy
- name: finemath-3plus
  paths:
  - s3://ai2-llm/preprocessed/finemath/finemath-3plus/allenai/dolma2-tokenizer/*.npy
- name: pes2o
  paths:
  - s3://ai2-llm/preprocessed/pes2o/allenai/dolma2-tokenizer/*.npy
- name: s2pdfv1
  topics:
  - name: adult
    paths:
    - s3://ai2-llm/preprocessed/s2pdf_dedupe_minhash_v1_with_no_pii_basic_quality_datadelve/adult/*.npy
  - name: art_design
    paths:
    - s3://ai2-llm/preprocessed/s2pdf_dedupe_minhash_v1_with_no_pii_basic_quality_datadelve/art_design/*.npy
  - name: crime_law
    paths:
    - s3://ai2-llm/preprocessed/s2pdf_dedupe_minhash_v1_with_no_pii_basic_quality_datadelve/crime_law/*.npy
  - name: education_jobs
    paths:
    - s3://ai2-llm/preprocessed/s2pdf_dedupe_minhash_v1_with_no_pii_basic_quality_datadelve/education_jobs/*.npy
  - name: entertainment
    paths:
    - s3://ai2-llm/preprocessed/s2pdf_dedupe_minhash_v1_with_no_pii_basic_quality_datadelve/entertainment/*.npy
  - name: fashion_beauty
    paths:
    - s3://ai2-llm/preprocessed/s2pdf_dedupe_minhash_v1_with_no_pii_basic_quality_datadelve/fashion_beauty/*.npy
  - name: finance_business
    paths:
    - s3://ai2-llm/preprocessed/s2pdf_dedupe_minhash_v1_with_no_pii_basic_quality_datadelve/finance_business/*.npy
  - name: food_dining
    paths:
    - s3://ai2-llm/preprocessed/s2pdf_dedupe_minhash_v1_with_no_pii_basic_quality_datadelve/food_dining/*.npy
  - name: games
    paths:
    - s3://ai2-llm/preprocessed/s2pdf_dedupe_minhash_v1_with_no_pii_basic_quality_datadelve/games/*.npy
  - name: health
    paths:
    - s3://ai2-llm/preprocessed/s2pdf_dedupe_minhash_v1_with_no_pii_basic_quality_datadelve/health/*.npy
  - name: home_hobbies
    paths:
    - s3://ai2-llm/preprocessed/s2pdf_dedupe_minhash_v1_with_no_pii_basic_quality_datadelve/home_hobbies/*.npy
  - name: industrial
    paths:
    - s3://ai2-llm/preprocessed/s2pdf_dedupe_minhash_v1_with_no_pii_basic_quality_datadelve/industrial/*.npy
  - name: literature
    paths:
    - s3://ai2-llm/preprocessed/s2pdf_dedupe_minhash_v1_with_no_pii_basic_quality_datadelve/literature/*.npy
  - name: politics
    paths:
    - s3://ai2-llm/preprocessed/s2pdf_dedupe_minhash_v1_with_no_pii_basic_quality_datadelve/politics/*.npy
  - name: religion
    paths:
    - s3://ai2-llm/preprocessed/s2pdf_dedupe_minhash_v1_with_no_pii_basic_quality_datadelve/religion/*.npy
  - name: science_tech
    paths:
    - s3://ai2-llm/preprocessed/s2pdf_dedupe_minhash_v1_with_no_pii_basic_quality_datadelve/science_tech/*.npy
  - name: software_dev
    paths:
    - s3://ai2-llm/preprocessed/s2pdf_dedupe_minhash_v1_with_no_pii_basic_quality_datadelve/software_dev/*.npy
  - name: software
    paths:
    - s3://ai2-llm/preprocessed/s2pdf_dedupe_minhash_v1_with_no_pii_basic_quality_datadelve/software/*.npy
  - name: sports_fitness
    paths:
    - s3://ai2-llm/preprocessed/s2pdf_dedupe_minhash_v1_with_no_pii_basic_quality_datadelve/sports_fitness/*.npy
  - name: transportation
    paths:
    - s3://ai2-llm/preprocessed/s2pdf_dedupe_minhash_v1_with_no_pii_basic_quality_datadelve/transportation/*.npy
  - name: travel
    paths:
    - s3://ai2-llm/preprocessed/s2pdf_dedupe_minhash_v1_with_no_pii_basic_quality_datadelve/travel/*.npy
- name: wikipedia
  paths:
  - s3://ai2-llm/preprocessed/structured-wikipedia/concat_with_links/allenai/dolma2-tokenizer/*.npy
nonzero_weight:
- arxiv
- dclm
- stack-edu
- finemath-3plus
- pes2o
- s2pdfv1
- wikipedia
manual_prior:
  arxiv: 0.046415989442928116
  dclm: 0.4301397640495781
  finemath-3plus: 0.13623189579133213
  pes2o: 0.00034916742857083816
  s2pdfv1: 0.011319294693709587
  stack-edu: 0.37537134737790623
  wikipedia: 0.000172541213210276
manual_topic_prior:
  dclm:adult_content: 0.0017286684366006405
  dclm:art_and_design: 0.00858070609713325
  dclm:crime_and_law: 0.004287352379446499
  dclm:education_and_jobs: 0.01256308517720726
  dclm:electronics_and_hardware: 0.061160548202094565
  dclm:entertainment: 0.007968902882399292
  dclm:fashion_and_beauty: 0.07340773816930295
  dclm:finance_and_business: 0.010046183599847503
  dclm:food_and_dining: 0.0016393488838472947
  dclm:games: 0.011317967766432967
  dclm:health: 0.0461776830399198
  dclm:history_and_geography: 0.005655392955855227
  dclm:home_and_hobbies: 0.012475914906313534
  dclm:industrial: 0.0035353041161660824
  dclm:literature: 0.03150446870194185
  dclm:politics: 0.05111504264165279
  dclm:religion: 0.006116218409189832
  dclm:science_math_and_technology: 0.04263367224393937
  dclm:social_life: 0.011469199017702715
  dclm:software: 3.3598853007610455e-05
  dclm:software_development: 0.005428048062279021
  dclm:sports_and_fitness: 0.009100722467522391
  dclm:transportation: 0.004389143181337099
  dclm:travel_and_tourism: 0.007804853858438472
  stack-edu:C: 0.009357259515994067
  stack-edu:CSharp: 0.008608551397182583
  stack-edu:Cpp: 0.039984352685079105
  stack-edu:Go: 0.005594380463516436
  stack-edu:Java: 0.06933459019128037
  stack-edu:JavaScript: 0.035547887550575044
  stack-edu:Markdown: 0.08245890242042783
  stack-edu:PHP: 0.008746335491813294
  stack-edu:Python: 0.07207133023210475
  stack-edu:Ruby: 0.005547103219508874
  stack-edu:Rust: 0.005673788527492571
  stack-edu:SQL: 0.006253222989121497
  stack-edu:Shell: 0.010170551456245116
  stack-edu:Swift: 0.006040076093050209
  stack-edu:TypeScript: 0.009983015144514506
