name: backfill-5xC-30m-superswarm-s2pdfv2-to-s2pdfv1-minimum-exact-seed-2-6T
description: 30M @ 5xC swarm on s2pdfv1 + existing, where existing is superswarm mix computed with s2pdfv2 (rep=4 @ 6T), seed 2 exact (9b9103e3/eb29e47d68eb0d60)
budget: ai2/oe-base
workspace: ai2/dolma2
nodes: 1
gpus: 1
variants: 3
preemptible: true
max_tokens: 2910233600
allow_repetition: false
sequence_length: 2048
seed: 2
minimum_weight: 0.005
min_strength: 1
max_strength: 20
proxy_model_id: olmo_30m
tokenizer: dolma2
weka: false
dtype: uint32
priority: low
cluster: ai2/augusta-google-1
device_batch_size: 32
sources:
- name: existing
  topics:
  - name: algebraicstack
    paths:
    - s3://ai2-llm/preprocessed/proof-pile-2/v0_decontaminated/algebraic-stack/train/allenai/dolma2-tokenizer/**/*.npy
    weight: 0.008461740603179136
  - name: arxiv
    paths:
    - s3://ai2-llm/preprocessed/proof-pile-2/v0_decontaminated/arxiv/train/allenai/dolma2-tokenizer/*.npy
    weight: 0.014872964526089383
  - name: dclm:adult_content
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/adult_content/dolma2-tokenizer/*.npy
    weight: 0.03899750911725985
  - name: dclm:art_and_design
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/art_and_design/dolma2-tokenizer/*.npy
    weight: 0.0015657155067653765
  - name: dclm:crime_and_law
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/crime_and_law/dolma2-tokenizer/*.npy
    weight: 0.0069844460228727845
  - name: dclm:education_and_jobs
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/education_and_jobs/dolma2-tokenizer/*.npy
    weight: 0.005193581516784105
  - name: dclm:electronics_and_hardware
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/electronics_and_hardware/dolma2-tokenizer/*.npy
    weight: 0.008060129972221858
  - name: dclm:entertainment
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/entertainment/dolma2-tokenizer/*.npy
    weight: 0.03878727003764278
  - name: dclm:fashion_and_beauty
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/fashion_and_beauty/dolma2-tokenizer/*.npy
    weight: 0.00011958501157400844
  - name: dclm:finance_and_business
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/finance_and_business/dolma2-tokenizer/*.npy
    weight: 0.01625499820443873
  - name: dclm:food_and_dining
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/food_and_dining/dolma2-tokenizer/*.npy
    weight: 0.04025843975063833
  - name: dclm:games
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/games/dolma2-tokenizer/*.npy
    weight: 0.014867088226266353
  - name: dclm:health
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/health/dolma2-tokenizer/*.npy
    weight: 0.10090231664530872
  - name: dclm:history_and_geography
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/history_and_geography/dolma2-tokenizer/*.npy
    weight: 0.0009501450419410265
  - name: dclm:home_and_hobbies
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/home_and_hobbies/dolma2-tokenizer/*.npy
    weight: 0.07304011930108995
  - name: dclm:industrial
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/industrial/dolma2-tokenizer/*.npy
    weight: 0.001674316864101954
  - name: dclm:literature
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/literature/dolma2-tokenizer/*.npy
    weight: 0.02982181219406537
  - name: dclm:politics
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/politics/dolma2-tokenizer/*.npy
    weight: 0.0638570138106299
  - name: dclm:religion
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/religion/dolma2-tokenizer/*.npy
    weight: 0.007904055190601406
  - name: dclm:science_math_and_technology
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/science_math_and_technology/dolma2-tokenizer/*.npy
    weight: 0.17603848597753283
  - name: dclm:social_life
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/social_life/dolma2-tokenizer/*.npy
    weight: 2.5213744955081645e-05
  - name: dclm:software
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/software/dolma2-tokenizer/*.npy
    weight: 0.008497677186544948
  - name: dclm:software_development
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/software_development/dolma2-tokenizer/*.npy
    weight: 0.1285632750751931
  - name: dclm:sports_and_fitness
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/sports_and_fitness/dolma2-tokenizer/*.npy
    weight: 0.0900408752912458
  - name: dclm:transportation
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/transportation/dolma2-tokenizer/*.npy
    weight: 0.0019721925397974175
  - name: dclm:travel_and_tourism
    paths:
    - s3://ai2-llm/preprocessed/dclm/baseline_topic_classified_sample/travel_and_tourism/dolma2-tokenizer/*.npy
    weight: 0.008908805328374764
  - name: finemath-3plus
    paths:
    - s3://ai2-llm/preprocessed/finemath/finemath-3plus/allenai/dolma2-tokenizer/*.npy
    weight: 0.024383689853987058
  - name: pes2o
    paths:
    - s3://ai2-llm/preprocessed/pes2o/allenai/dolma2-tokenizer/*.npy
    weight: 0.001961703761291723
  - name: stack-edu:C
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/C/**/*.npy
    weight: 0.00297774510423966
  - name: stack-edu:CSharp
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/CSharp/**/*.npy
    weight: 0.004530708276759668
  - name: stack-edu:Cpp
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Cpp/**/*.npy
    weight: 0.007880018687588681
  - name: stack-edu:Go
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Go/**/*.npy
    weight: 0.0008795341975986693
  - name: stack-edu:Java
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Java/**/*.npy
    weight: 0.01971363753162255
  - name: stack-edu:JavaScript
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/JavaScript/**/*.npy
    weight: 0.005588748360834645
  - name: stack-edu:Markdown
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Markdown/**/*.npy
    weight: 0.018184599973487287
  - name: stack-edu:PHP
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/PHP/**/*.npy
    weight: 0.004650512985502479
  - name: stack-edu:Python
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Python/**/*.npy
    weight: 0.011330870424744484
  - name: stack-edu:Ruby
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Ruby/**/*.npy
    weight: 0.0008721013933959155
  - name: stack-edu:Rust
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Rust/**/*.npy
    weight: 0.0008920185354024846
  - name: stack-edu:Shell
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Shell/**/*.npy
    weight: 2.1991730966553537e-11
  - name: stack-edu:SQL
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/SQL/**/*.npy
    weight: 9.349705041669724e-11
  - name: stack-edu:Swift
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/Swift/**/*.npy
    weight: 0.0009496053317122904
  - name: stack-edu:TypeScript
    paths:
    - s3://ai2-llm/preprocessed/stack-edu/allenai/dolma2-tokenizer/TypeScript/**/*.npy
    weight: 0.0015695041353888783
  - name: wikipedia
    paths:
    - s3://ai2-llm/preprocessed/structured-wikipedia/concat_with_links/allenai/dolma2-tokenizer/*.npy
    weight: 0.0070152286438398105
- name: s2pdfv1
  paths:
  - s3://ai2-llm/preprocessed/s2pdf_dedupe_minhash_v1_with_no_pii_basic_quality_datadelve/**/*.npy
nonzero_weight:
- existing
- s2pdfv1
manual_prior:
  existing: 0.98
  s2pdfv1: 0.02
